[global]
    workgroup = MMAJIDI8
    security = ADS
    server role = member server
    realm = MMAJIDI8.NET

    kerberos method = secrets and keytab

    winbind use default domain = no
    winbind enum users = yes
    winbind enum groups = yes

    idmap config * : backend = tdb
    idmap config * : range = 10000-99999

    template shell = /bin/bash
    template homedir = /home/%U

    restrict anonymous = 2
    map to guest = Never

[homes]
    comment = Home Directories
    browseable = no
    read only = no
    valid users = %S

[Finance]
    path = /srv/shares/finance
    browseable = yes
    read only = no
    valid users = @"MMAJIDI8\finance"
    create mask = 0660
    force create mode = 0660
    directory mask = 2770
    force directory mode = 2770

[HR]
    path = /srv/shares/hr
    browseable = yes
    read only = no
    valid users = @"MMAJIDI8\hr"
    create mask = 0660
    force create mode = 0660
    directory mask = 2770
    force directory mode = 2770

[IT]
    path = /srv/shares/it
    browseable = yes
    read only = no
    valid users = @"MMAJIDI8\it"
    create mask = 0660
    force create mode = 0660
    directory mask = 2770
    force directory mode = 2770